language: php

php:
  - 5.6

env:
  - SYMFONY_VERSION=2.8.*  

services:
  - postgresql
  
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
  - psql -c 'create database symfony_pickomino;' -U postgres
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  # - composer require symfony/symfony:${SYMFONY_VERSION}
  - composer install
  - php app/console doctrine:schema:update --force

script: 
  - phpunit -c --debug app/
  - node_modules/karma/bin/karma start karma.conf.js --single-run
