language: php

php:
  - 5.6

addons:
  sonarqube: true

env:
  - SYMFONY_VERSION=2.8.*
  - secure: "WafrAAiAdbzRgowB42OZsywdCg6tShVz2KDXChqKu8qK+wA5+Iubzetds8HIpOpfPCpDt7EY4yew+VBoWFZbgcBAV/RNAdUz5TZdc4eJU/rcDrJ5uPRktulVTGRVNO5zzum+g6IkhNv3EXzt1IvNBMph7bMYrFZHc8+6sBf2ij1rDYOgtiWx1qAiYxx46lZvdJ+vRC6b19IsSVdVnmSBuHoucgbfnAfNEE1NHUnFdO0PKbZdFoh/nyCn8/tgPdgRQj0pbLye8rhejG6K+CMNKjhkvmDO4aKME/G/nimwX+AuuFaRZ2RKCEyRPbtw60NHZE2Siusbl3iyxpbQPhqffyJ49Ei7j/cbCtpuI9o5WsXJBBu6M2kGNuLs2vZxwO6j0TescoSvdJIGz35DJjF3nM+a2cBvDxRfxCJEQwYW1Q8mVuAxR9hDjdddZIzSE2PkyF61xmtxjNA9iuGCjIyoINqj31snrsXrO9prsMtRLaMQwXg+qe+wtChvyTCvyPXTfCQo3raYeaBzJ6OOY2wMPugGdlzAIxVY9GOunPOhVwRWCnXBfLsh1ckYTcePRWZHjr05Ng7dZ0KEiRMnaHLZkh18nVg5qPqegH6ctN+hs6Qp0uk9jjo8C6YpSbEZqp3o6N9Hxv598opmGPAs7N4cC97uDt4v4bPcLSiPXqjJzmM="

services:
  - postgresql

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
  - psql -c 'create database symfony_pickomino;' -U postgres
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:schema:update --force
script:
  - phpunit --debug -c app/
  - node_modules/karma/bin/karma start karma.conf.js --single-run
