language: php

php:
  - 5.6

addons:
  sonarqube: true

env:
  - SYMFONY_VERSION=2.8.*

  - SONAR_TOKEN:
    - secure: "mvjo2I0BAbh6MNGgTpQFJXvXkgHctfeoeBc/ajv0IG6VxhA40Aox0wVi3ZrprYDQHvmLH2FpVaFHq0IENqyqCsJb73B11mN0kQC+LR+wN4PmZhyhRNAxlkZRBF6gypTShTZJ6XDtBtsuLLDZcEbohMcr2oBdB4VB9HlEnbIWS9YfMaaaqJtytmebUj8sV5/H7eZynJUpywQL1FW4VjBKplWP8hV69CiHKk80brgUTZf7TcXRNOrcU+Hfvjjbsj8B36eDbFaP7e3TL5aMjKjVvwcd6H06HLTa1YpeYI9Gk3crsOgV0/sFyYC1B5mlptOGEP2/oI8O7Sn8WUErbeIO/AY+qyZm6n7oAdE2ZDmgQf+v/NU/ucwiKKvQq307ziLj4JWTF7nM3R8vhpQqrAE+JStPtyr41sCFQ4iEbDJl5uQyUS2h9k5z+1sek0CCfAcNZxgeOVjzZtD8wrAWkYkvBciedxc8wDpGHWgNu5Dl7uewVCJc/4koIN8MYGDdwvshTpLsa72u8S3InfSJtcRMvQQ/rm5gBYAgcJuXO3TaVGNdaG9luo2xqIwB369julWFQV3WH+obzYVeH/FH5wX2c0Y6hr+W0WTi1v4ZwqG9zWZ28m14JDgKwTHt4I1ny431cER1wcQQIXWpbh+yubqkYQiAKTQQzkYtp4YGMFQlxFo="

services:
  - postgresql

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
  - psql -c 'create database symfony_pickomino;' -U postgres
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:schema:update --force
script:
  - phpunit --debug -c app/
  - node_modules/karma/bin/karma start karma.conf.js --single-run
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
