language: php

php:
  - 5.6

addons:
  sonarqube: true

env:
  - SYMFONY_VERSION=2.8.*

services:
  - postgresql

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
  - psql -c 'create database symfony_pickomino;' -U postgres
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:schema:update --force
script:
  - phpunit --debug -c app/
  - node_modules/karma/bin/karma start karma.conf.js --single-run
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN

SONAR_TOKEN:
  - secure: lHbYhND4Wg/kxnMHuXRX9A3CzL10oVPFgXFcXRN0xwXxmJBl8E+phPJClp8QPWd66F0rUmQfh09UdVhaXUEIv0HDlIfs5uCUNeYnUict6853QKZ3u3fSdNXGhTVfapdzVOT9oOcj4pydQkSfSh7ZapuyWaRQucFmvQBTNmeJJQY4XdET4P/vmzpKnxzETWk9EScEgv97Uma7UvNXMozDKz1GMMHWPfgf0p4iugXNoAoavtcWHnlJUo6jcFsaOQE4RRVFPd7z6F8eRx2ec3UJKAf0IZAMIZI1KjC1FR1Mkz4pWTzz9en+xvFF9fz2UuMOM64nppPaWt08GR0eoZPR80xgNlDVPKSkuwaBQe6dEj/kIXtWFbFmo+Kp4za+9w8+3PtG08wmsXzZE9D/8KLzFkrq25iE1AyBPK1DoBjT78bMIJghMRJSjD4Q6aHTwSNcmL+0P3TF0O4+YrP/pjttAtJiz/N8beUMTylSIMdeixsArm8SLUrJCbVbER/uLNP3DzmO6UG/wfBS5NHAuilnECp3x48VINvCenEfDq1i1ADR2hIVDe1wlIr6XkIb4C8Wy9R2GlsUjzrvxhBXN40BZXO6rY8nmEmSoEMai6WduO1yDgrf5KKjaNlI2kkrJqpsUA/AKPdzYruRj4rVlj6Wnb1uDJNvzhlXw5tD6WyGpLA=
