# src/AppBundle/Resources/config/services.yml

services:
    admin.player:
         class: AppBundle\Admin\PlayerAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, label: Player }
         arguments: [null, AppBundle\Entity\Player, AppBundle:PlayerAdmin]


    admin.game:
         class: AppBundle\Admin\GameAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, label: Game }
         arguments: [null, AppBundle\Entity\Game, AppBundle:GameAdmin]


    admin.gamestate:
         class: AppBundle\Admin\GameStateAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, label: GameState }
         arguments: [null, AppBundle\Entity\GameState, AppBundle:GameStateAdmin]
