# src/AppBundle/Resources/config/services.yml

services:
    app.admin.player:
         class: AppBundle\Admin\PlayerAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, group: appbundle, label: Player }
         arguments: [null, AppBundle\Entity\Player, AppBundle:PlayerAdmin]


    app.admin.game:
         class: AppBundle\Admin\GameAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, group: appbundle, label: Game }
         arguments: [null, AppBundle\Entity\Game, AppBundle:GameAdmin]


    app.admin.gamestate:
         class: AppBundle\Admin\GameStateAdmin
         tags:
             - { name: sonata.admin, manager_type: orm, group: appbundle, label: GameState }
         arguments: [null, AppBundle\Entity\GameState, AppBundle:GameStateAdmin]
